---
- name: Safari - Don't send search queries to Apple
  osx_defaults:
    domain: com.apple.Safari
    key: "{{ item.key }}"
    type: bool
    value: "{{ item.value }}"
    state: present
  with_items:
    - key: UniversalSearchEnabled
      value: false
    - key: SuppressSearchSuggestions
      value: true

- name: Safari - Show full URL in the address bar
  osx_defaults:
    domain: com.apple.Safari
    key: ShowFullURLInSmartSearchField
    type: bool
    value: true
    state: present

- name: Safari - Enable debug, develop, web inspector
  osx_defaults:
    domain: com.apple.Safari
    key: "{{ item }}"
    type: bool
    value: true
    state: present
  with_items:
    - IncludeInternalDebugMenu
    - IncludeDevelopMenu
    - WebKitDeveloperExtrasEnabledPreferenceKey
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled

- name: Safari - Enable continuous spellchecking
  osx_defaults:
    domain: com.apple.Safari
    key: WebContinuousSpellCheckingEnabled
    type: bool
    value: true
    state: present

- name: Safari - Disable AutoFill
  osx_defaults:
    domain: com.apple.Safari
    key: "{{ item }}"
    type: bool
    value: false
    state: present
  with_items:
    - AutoFillFromAddressBook
    - AutoFillPasswords
    - AutoFillCreditCardData
    - AutoFillMiscellaneousForms

- name: Safari - Enable “Do Not Track”
  osx_defaults:
    domain: com.apple.Safari
    key: SendDoNotTrackHTTPHeader
    type: bool
    value: true
    state: present

- name: Safari - Update extensions automatically
  osx_defaults:
    domain: com.apple.Safari
    key: InstallExtensionUpdatesAutomatically
    type: bool
    value: true
    state: present