---
- name: Install necessary zsh homebrew packages
  community.general.homebrew:
    name:
      - zsh
      - zsh-completions
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
  tags: zsh

- name: Check for .oh-my-zsh exists
  ansible.builtin.stat:
    path: /Users/{{ username }}/.oh-my-zsh
  register: ohmyzsh_folder
  tags: zsh

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL {{ ohmyzsh.url }})"
  when: not ohmyzsh_folder.stat.exists
  changed_when: true
  tags: zsh

# - name: Install powerlevel10k theme
#   ansible.builtin.git:
#     repo: "{{ powerlevel10k.theme.url }}"
#     dest: "/Users/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
#     version: "{{ powerlevel10k.theme.version }}"
#   tags: zsh
- name: Install spaceship theme
  ansible.builtin.git:
    repo: "{{ spaceship.theme.url }}"
    dest: "/Users/{{ username }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    version: "{{ spaceship.theme.version }}"
  tags: zsh

- name: Copy zsh configuration files
  tags: zsh
  block:
    - name: Copy .zshrc
      ansible.builtin.template:
        src: "zsh/.zshrc.j2"
        dest: "/Users/{{ username }}/.zshrc"
        mode: "0644"

    # - name: Copy .p10k.zsh
    #   ansible.builtin.copy:
    #     src: "zsh/.p10k.zsh"
    #     dest: "/Users/{{ username }}/.p10k.zsh"
    #     mode: "0644"

- name: Set default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
  tags: zsh
