---
- name: Install necessary tmux homebrew packages
  homebrew:
    name: ["tmux", "reattach-to-user-namespace"]
    state: present

- name: Copy custom tmux config
  copy:
    src: tmux/.tmux.conf
    dest: /Users/{{ username }}/.tmux.conf

- name: Create tmux plugin directory
  file:
    dest: /Users/{{ username }}/.tmux/plugins
    state: directory

- name: Install plugins
  git:
    repo: "{{ item.repo }}"
    dest: "/Users/{{ username }}/.tmux/plugins/{{ item.name }}"
    version: "{{ item.version }}"
    force: yes
  with_items: "{{ tmux_plugins }}"

- name: Add binary scripts for bottom bar
  copy:
    src: tmux/bin/
    dest: "/Users/{{ username }}/bin"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755